# Generated by Django 3.1.6 on 2021-02-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
