# Generated by Django 3.1.6 on 2021-04-01 03:22

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialty', '__first__'),
        ('plan', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, default='store/default.svg', null=True, upload_to='store', validators=[store.validators.validate_image_square])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, validators=[store.validators.valite_cnpj], verbose_name='CNPJ')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialty.specialty')),
            ],
            options={
                'ordering': ['created_at', 'updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreWallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', sorl.thumbnail.fields.ImageField(blank=True, default='store/wallpaper/default.svg', null=True, upload_to='store/wallpaper')),
                ('store', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallpaper', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='StorePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
                ('store', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='store.store')),
            ],
            options={
                'ordering': ['created_at', 'updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', sorl.thumbnail.fields.ImageField(blank=True, default='store/avatar/default.svg', null=True, upload_to='store/avatar')),
                ('store', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ddd', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=9)),
                ('main', models.BooleanField(default=True)),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='store.store')),
            ],
            options={
                'ordering': ['created_at', 'updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='store.openday')),
            ],
            options={
                'ordering': ['created_at', 'updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='openday',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='store.store'),
        ),
        migrations.AlterUniqueTogether(
            name='openday',
            unique_together={('day_of_week', 'store')},
        ),
    ]
