# Generated by Django 3.1.6 on 2021-04-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='main',
            new_name='whatsapp',
        ),
    ]
