# Generated by Django 3.1.6 on 2021-02-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20210210_1947'),
        ('store', '0003_auto_20210210_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
