# Generated by Django 3.1.6 on 2021-02-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210219_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='image',
            new_name='logo',
        ),
    ]
