# Generated by Django 3.1.6 on 2021-02-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210219_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
