# Generated by Django 3.1.6 on 2021-02-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
    ]
