# Generated by Django 3.1.6 on 2021-03-26 19:09

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210220_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='average_image/default.png', null=True, upload_to='store'),
        ),
    ]
