# Generated by Django 3.1.6 on 2021-02-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storeplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='plan',
        ),
    ]
