# Generated by Django 3.1.6 on 2021-02-10 23:45

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[store.validators.valite_cnpj], verbose_name='CNPJ'),
        ),
    ]
