# Generated by Django 3.1.6 on 2021-02-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_store_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeplan',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
