# Generated by Django 3.1.6 on 2021-03-26 19:40

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210326_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='store/default.svg', null=True, upload_to='store'),
        ),
    ]
