# Generated by Django 3.1.6 on 2021-02-14 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_description'),
        ('store', '0008_auto_20210214_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
        ),
    ]
