# Generated by Django 3.1.6 on 2021-02-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210210_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
