# Generated by Django 3.1.6 on 2021-03-29 03:23

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210328_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', sorl.thumbnail.fields.ImageField(blank=True, default='store/default.svg', null=True, upload_to='store/avatar', validators=[store.validators.validate_image_square])),
                ('store', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='store.store')),
            ],
        ),
    ]
