# Generated by Django 3.1.6 on 2021-02-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0001_initial'),
        ('store', '0009_store_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialty.specialty'),
        ),
    ]
