# Generated by Django 3.1.6 on 2021-02-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storeplan_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openday',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='opentime',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='storeplan',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='openday',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opentime',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storeplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
