# Generated by Django 3.1.6 on 2021-03-29 04:22

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storeavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='store/default.svg', null=True, upload_to='store'),
        ),
        migrations.AlterField(
            model_name='storeavatar',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='store/default.svg', null=True, upload_to='store/avatar'),
        ),
    ]
