# Generated by Django 3.1.6 on 2021-02-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210211_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
