# Generated by Django 3.1.6 on 2021-03-29 12:38

from django.db import migrations
import sorl.thumbnail.fields
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210329_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='store/default.svg', null=True, upload_to='store', validators=[store.validators.validate_image_square]),
        ),
    ]
