# Generated by Django 3.1.6 on 2021-03-29 13:25

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210329_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeavatar',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='store/avatar/default.svg', null=True, upload_to='store/avatar'),
        ),
        migrations.CreateModel(
            name='StoreWallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', sorl.thumbnail.fields.ImageField(blank=True, default='store/wallpaper/default.svg', null=True, upload_to='store/wallpaper')),
                ('store', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='wallpaper', to='store.store')),
            ],
        ),
    ]
