# Generated by Django 3.1.6 on 2021-02-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210211_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
    ]
