# Generated by Django 3.1.6 on 2021-03-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210329_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeavatar',
            name='store',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='store.store'),
        ),
        migrations.AlterField(
            model_name='storewallpaper',
            name='store',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallpaper', to='store.store'),
        ),
    ]
