# Generated by Django 3.1.6 on 2021-02-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='city',
        ),
    ]
