# Generated by Django 3.1.6 on 2021-02-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_store_address'),
        ('address', '0003_auto_20210210_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city'),
        ),
    ]
