# Generated by Django 3.1.6 on 2021-03-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210328_1712'),
        ('address', '0003_auto_20210327_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='store',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='store.store'),
        ),
    ]
