# Generated by Django 3.1.6 on 2021-02-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20210210_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
    ]
