# Generated by Django 3.1.6 on 2021-02-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20210210_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
