# Generated by Django 3.1.6 on 2021-02-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_store_specialty'),
        ('address', '0008_address_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
