# Generated by Django 3.1.6 on 2021-02-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'Specialties'},
        ),
    ]
