# Generated by Django 3.1.6 on 2021-02-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
