# Generated by Django 3.1.6 on 2021-02-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
