# Generated by Django 3.1.6 on 2021-02-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20210214_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='value',
            new_name='price',
        ),
    ]
